## For Regression data set

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','LPA'])

In [3]:
df

,cgpa,profile_score,LPA
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [4]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for i in range(1,L):
        parameters['W'+str(i)] = np.ones((layer_dims[i-1],layer_dims[i]))*0.1
        parameters["B"+str(i)] = np.zeros((layer_dims[i],1))
    
    return parameters

        


In [5]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'B1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'B2': array([[0.]])}

In [6]:
def linear_forward(A_prev, W,b):
    Z = np.dot(W.T, A_prev) + b 
    return Z



#  to check the inner side 
print(parameters['B2'])
print(parameters['W2'].T)





NameError: name 'parameters' is not defined

In [ ]:
# forward prop
def L_layer_forward(X,parameter):
    A = X 
    L = len(parameter)//2
    for i in range(1,L+1):
        A_prev = A
        #print("A_prev",A_prev)
        
        W = parameter['W'+str(i)]
        b = parameter['B'+str(i)]
        #print(f'Weight{i} is {W}')
        #print(f'bias{i} is {b}')
        


        
        A = linear_forward(A_prev,W,b) 
    return A,A_prev


In [ ]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1)
Y = df['LPA'].values[0]
parameters = initialize_parameters([2,2,1])
len(parameters)
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'B1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'B2': array([[0.]])}

In [ ]:
Y_hat , A1 =L_layer_forward(X,parameters)
Y_hat=Y_hat[0][0]




In [ ]:
A1[0][0]
parameters['W1']



array([[0.1, 0.1],
       [0.1, 0.1]])

In [ ]:
def update_parameters(parameters,Y,Y_hat,A1,X):
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2*(Y-Y_hat)*A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2*(Y-Y_hat)*A1[1][0])
    parameters['B2'][0][0] = parameters['B2'][0][0] + (0.001 * 2*(Y-Y_hat))
    
    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2*(Y-Y_hat)*parameters["W2"][0][0]*X[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2*(Y-Y_hat)*parameters['W2'][0][0]*X[1][0])
    parameters['B1'][0][0] = parameters['B1'][0][0] + (0.001 * 2*(Y-Y_hat)*parameters['W2'][0][0])
      
    parameters['W1'][1][0] = parameters['W1'][1][0] +( 0.001 * 2*(Y-Y_hat)*parameters["W2"][1][0]*X[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2*(Y-Y_hat)*parameters['W2'][1][0]*X[1][0])
    parameters['B1'][1][0] = parameters['B1'][1][0] + (0.001 * 2*(Y-Y_hat)*parameters['W2'][1][0])


    
    

In [ ]:
update_parameters(parameters,Y,Y_hat,A1,X)

In [ ]:
#X = df[['cgpa','profile_score']].values[3].reshape(2,1)
##Y = df['LPA'].values[3]
#parameters = initialize_parameters([2,2,1])
#len(parameters)
#parameters

In [ ]:
parameters

{'W1': array([[7.6225088, 7.6225088],
        [7.6225088, 7.6225088]]),
 'B1': array([[0.9403136],
        [0.9403136]]),
 'W2': array([[1.2776],
        [1.2776]]),
 'B2': array([[0.736]])}

In [ ]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 10

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) 
    y = df['LPA'].values[j]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,Y,Y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  26.609404847272543
Epoch -  2 Loss -  21.971059673284614
Epoch -  3 Loss -  14.320642571350543
Epoch -  4 Loss -  4.071207881588833
Epoch -  5 Loss -  2.285033177056581
Epoch -  6 Loss -  71.88849570698454
Epoch -  7 Loss -  501.6894939512356
Epoch -  8 Loss -  2520.5043101925457
Epoch -  9 Loss -  11188.697339583008
Epoch -  10 Loss -  47029.39726524371


{'W1': array([[1.82082826, 2.76042751],
        [2.33773713, 3.56748471]]),
 'B1': array([[0.26907334],
        [0.35032955]]),
 'W2': array([[3.00901866],
        [4.19923293]]),
 'B2': array([[0.2944]])}

# know using keras 

In [ ]:
df

,cgpa,profile_score,LPA
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/Users/All file hear/complete ai /Deep learning/.venv/lib/python3.13/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weight = [
    np.array([[0.1, 0.1],
              [0.1, 0.1]], dtype=np.float32),

    np.array([0, 0], dtype=np.float32),

    np.array([[0.1],
              [0.1]], dtype=np.float32),

    np.array([0], dtype=np.float32)
]

In [ ]:
model.set_weights(new_weight)

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)

In [ ]:
model.compile(loss ='mean_squared_error',optimizer=optimizer)

In [ ]:
X = df.drop(columns=['LPA'])
Y = df['LPA']
X.values

array([[ 8,  8],
       [ 7,  9],
       [ 6, 10],
       [ 5, 12]])

In [ ]:
model.fit(X.values,Y.values,epochs=75,batch_size=1,verbose=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18.5585
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18.0527
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17.4779
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16.9821
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16.4430
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15.8959
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15.3081
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 14.7825
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14.2967
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.7229
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.2335
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.6579
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.1662
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.6444
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.1797
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━━

In [ ]:
model.get_weights()

[array([[0.37893015, 0.37893015],
        [0.394673  , 0.394673  ]], dtype=float32),
 array([0.28954715, 0.28954715], dtype=float32),
 array([[0.3920001],
        [0.3920001]], dtype=float32),
 array([0.21505721], dtype=float32)]

## For classification

In [137]:
df2 = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns=['cgpa','profile_score','LPA'])

In [8]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'B1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'B2': array([[0.]])}

In [9]:
def segmoid(Z):
     A = 1/ (1+np.exp(-Z))
     return A

In [10]:
def linear_forward(A_prev, W,b):
    Z = np.dot(W.T, A_prev) + b 
    A = segmoid(Z)
    return Z


In [128]:
# forward prop
def L_layer_forward2(X,parameter):
    A = X 
    L = len(parameter)//2
    for i in range(1,L+1):
        A_prev = A
        W = parameter['W'+str(i)]
        b = parameter['B'+str(i)]        
        A = linear_forward(A_prev,W,b) 
    return A,A_prev


In [20]:
def update_parameters2(parameters,Y,Y_hat,A1,X):
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * (Y-Y_hat)*A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 *(Y-Y_hat)*A1[1][0])
    parameters['B2'][0][0] = parameters['B2'][0][0] + (0.001 * (Y-Y_hat))
    
    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * (Y-Y_hat)*parameters["W2"][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * (Y-Y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
    parameters['B1'][0][0] = parameters['B1'][0][0] + (0.001 * (Y-Y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))
      
    parameters['W1'][1][0] = parameters['W1'][1][0] +( 0.001 * (Y-Y_hat)*parameters["W2"][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * (Y-Y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
    parameters['B1'][1][0] = parameters['B1'][1][0] + (0.001 * (Y-Y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))


    
    

In [139]:
X = df2[['cgpa','profile_score']].values[0].reshape(2,1)
Y = df2['LPA'].values[0]
#parameters = initialize_parameters([2,2,1])

Y_hat, A1 = L_layer_forward(X,parameters)
Y_hat = Y_hat[0][0]



In [121]:
update_parameters2(parameters,Y,Y_hat,A1,X)


In [123]:
print(-Y*np.log(Y_hat)-(1-Y)*np.log(1-Y_hat))

2.297807649467193


In [103]:
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'B1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'B2': array([[0.]])}

In [140]:
X = df2[['cgpa','profile_score']].values[1].reshape(2,1)
Y = df2['LPA'].values[1]
#parameters = initialize_parameters([2,2,1])

Y_hat, A1 = L_layer_forward(X,parameters)
Y_hat = Y_hat[0][0]

parameters

{'W1': array([[ 0.08463773, -0.18147328],
        [ 0.04859566,  0.16233027]]),
 'B1': array([[-0.0151757 ],
        [ 0.00258228]]),
 'W2': array([[2.20583104],
        [0.9907864 ]]),
 'B2': array([[2.07990108]])}

In [108]:
print(-Y*np.log(Y_hat)-(1-Y)*np.log(1-Y_hat))

3.8928773946702395


In [109]:
update_parameters2(parameters,Y,Y_hat,A1,X)


In [141]:
X = df2[['cgpa','profile_score']].values[2].reshape(2,1)
Y = df2['LPA'].values[2]
#parameters = initialize_parameters([2,2,1])

Y_hat, A1 = L_layer_forward(X,parameters)
Y_hat = Y_hat[0][0]

parameters

{'W1': array([[ 0.08463773, -0.18147328],
        [ 0.04859566,  0.16233027]]),
 'B1': array([[-0.0151757 ],
        [ 0.00258228]]),
 'W2': array([[2.20583104],
        [0.9907864 ]]),
 'B2': array([[2.07990108]])}

In [111]:
print(-Y*np.log(Y_hat)-(1-Y)*np.log(1-Y_hat))

4.238352147542699


In [112]:
update_parameters2(parameters,Y,Y_hat,A1,X)


In [142]:
X = df2[['cgpa','profile_score']].values[3].reshape(2,1)
Y = df2['LPA'].values[3]
#parameters = initialize_parameters([2,2,1])

Y_hat, A1 = L_layer_forward(X,parameters)
Y_hat = Y_hat[0][0]

parameters

{'W1': array([[ 0.08463773, -0.18147328],
        [ 0.04859566,  0.16233027]]),
 'B1': array([[-0.0151757 ],
        [ 0.00258228]]),
 'W2': array([[2.20583104],
        [0.9907864 ]]),
 'B2': array([[2.07990108]])}

In [ ]:
print(-Y*np.log(Y_hat)-(1-Y)*np.log(1-Y_hat))

3.817965326024675


In [146]:
update_parameters2(parameters,Y,Y_hat,A1,X)
df2


,cgpa,profile_score,LPA
0,8,8,1
1,7,9,1
2,6,10,0
3,5,5,0


In [151]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 1000

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df2[['cgpa', 'profile_score']].values[j].reshape(2,1) 
    y = df2['LPA'].values[j]

    # Parameter initialization


    y_hat,A1 = L_layer_forward2(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters2(parameters,y,y_hat,A1,X)

    Loss.append(-y*np.log(y_hat)-(1-y)*np.log(1-y_hat))

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  0.7226409132810659
Epoch -  2 Loss -  0.7199303929978415
Epoch -  3 Loss -  0.7173685549244734
Epoch -  4 Loss -  0.7149435473207086
Epoch -  5 Loss -  0.7126446578162371
Epoch -  6 Loss -  0.7104621851791708
Epoch -  7 Loss -  0.7083873277039501
Epoch -  8 Loss -  0.706412085786036
Epoch -  9 Loss -  0.7045291766466059
Epoch -  10 Loss -  0.7027319594955093
Epoch -  11 Loss -  0.7010143696887835
Epoch -  12 Loss -  0.6993708606589578
Epoch -  13 Loss -  0.6977963525808267
Epoch -  14 Loss -  0.6962861868892529
Epoch -  15 Loss -  0.6948360858943665
Epoch -  16 Loss -  0.6934421168477197
Epoch -  17 Loss -  0.6921006599041235
Epoch -  18 Loss -  0.6908083795009362
Epoch -  19 Loss -  0.6895621987418944
Epoch -  20 Loss -  0.6883592764280968
Epoch -  21 Loss -  0.6871969864260763
Epoch -  22 Loss -  0.6860728991033477
Epoch -  23 Loss -  0.6849847645964656
Epoch -  24 Loss -  0.6839304977063946
Epoch -  25 Loss -  0.6829081642416136
Epoch -  26 Loss -  0.6819159686514

{'W1': array([[0.0314416 , 0.03906634],
        [0.0979621 , 0.04522464]]),
 'B1': array([[-0.01626734],
        [-0.01173218]]),
 'W2': array([[0.29220758],
        [0.29007451]]),
 'B2': array([[0.06357894]])}

In [136]:
df

,cgpa,profile_score,LPA
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7
